name: CD Compute

on:
  push:
    branches:
      - "preprod"
      - "prod"

  workflow_dispatch:
    inputs:
      env_conf_id:
        required: false
        description: |
          Env conf id.
          Optional, if set then Deployment id must remain unset (as we will create a new Deployment id). If not set, then will retrieve latest conf.
      deployment_id:
        required: false
        description: |
          Deployment id.
          Optional, if set then Env conf id must remain unset (as we already have an associated Env conf id).
          Mainly used by Poja API: regular users does not have to use it under normal conditions.
jobs:
  initiate-deployment:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4.1.6

      - uses: actions/setup-java@v4.2.1
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Prepare build
        run: |
          chmod +x ./gradlew
          chmod +x .shell/publish_gen_to_maven_local.sh

      - name: Build project
        run: sam build
